---
- name: Create Conf File
  file:
    path: /etc/nginx/sites-available/{{ hostname }}
    state: touch

- name: change nginx configuration file
  blockinfile:
    path: /etc/nginx/sites-available/{{ hostname }} 
    block: |
      server {
      listen 80;
      listen [::]:80;
      root /var/www/{{ hostname }}; 
      index  index.php index.html index.htm;
      server_name  {{ hostname }} www.{{ hostname }};
      client_max_body_size 100M;
      autoindex off;
      location / {
        try_files $uri $uri/ =404;
      }
      location ~ [^/].php(/|$) {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }
      }
    state: present

- name: Create link
  file:
    src: /etc/nginx/sites-available/{{ hostname }}
    dest: /etc/nginx/sites-enabled/{{ hostname }}
    state: link

- name: remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add default page
  template:
    src: index.html.j2
    dest: /var/www/{{ hostname }}/index.html
  when: "wordpress_path != '/'"

- name: restart nginx
  service:
    name: nginx
    state: restarted
